enum RecentActionTypes {
    ADD_RECENT_TEAM = 'ADD_RECENT_TEAM',
    ADD_RECENT_USER = 'ADD_RECENT_USER',
    ADD_RECENT_TOURNAMENT = 'ADD_RECENT_TOURNAMENT',
    RESET_RECENT = 'RESET_RECENT',
}

export default RecentActionTypes;
